var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/ai-assistant/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oe.7o~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0c5jrzf.js")
R.c("server/chunks/ssr/[root-of-the-server]__040qnf4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ngiev5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v7s5ip._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_ai-assistant_page_actions_0ry5jd2.js")
R.m(57044)
module.exports=R.m(57044).exports
